### ISSUE TITLE
Can not find module if baseurl set '.' and rootDir to '.' in tsconfig with ts-node

### ISSUE THREAD

**Issue by sakeyu** [sleep-written/bleed-believer#2]
If i set the baseurl to '.' in tsconfig, load modules in node_modules will make a error:

![image](https://user-images.githubusercontent.com/3366123/220857239-bdd95fad-755c-451f-87b7-a0cb89584576.png)

I think the problem is caused by load function(the code below is modified to resolve this problem):

<img width="937" alt="image" src="https://user-images.githubusercontent.com/3366123/220857603-8480bed8-6eb3-4dfc-b4d0-e96b9688b1b0.png">

If i set baseurl to '.' and load from node_modules, the base variable will be seted to rootDir, and path.startsWith(base) will be true.

I think probably it could test the path if there are modules loaded from node_modules, ignore it.

**Comment by sleep-written** [comment]
Solved in the [new release](https://github.com/sleep-written/bleed-believer/releases/tag/%40bleed-believer%2Fpath-alias%400.12.0). Please update your dependency and tell me if it works.

**Comment by sakeyu** [comment]
I am sorry that it did not work yet, the regExp's test behavior  is strange somethings when with global flag.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/3366123/221097717-ca4ad90d-b8c3-454a-90ba-bf86e48c7699.png">

So, if i load modules from node_modules one by one, the second load will failed because of that.

**Comment by sleep-written** [comment]
Check with the new [patch update](https://github.com/sleep-written/bleed-believer/releases/tag/%40bleed-believer%2Fpath-alias%400.12.1). At the top of this repositoy, check the folder `/examples/path-alias`, which contains the project that i use to test your escenario. Tell me if you still have issues with this package.

**Comment by sakeyu** [comment]
Prefect, it works right now, thank you very much!
