### ISSUE TITLE
Will the dependency of typescript be upgraded to 5 ?

### ISSUE THREAD

**Issue by sakeyu** [sleep-written/bleed-believer#4]
If i specify the version of typescript to 5.0 manually, then the dependency will broken.

**Comment by sleep-written** [comment]
I don't know, I'll tests all packages of this monorepo with Typescript 5. As soon my packages works with the new version I'll upgrade all packages.

**Comment by sleep-written** [comment]
Ok, I was testing implementing Typescript 5 in all the monorepo, and it's a breaking change is I use some options related to __isolated modules__. In this week i'll analyze how to make this upgrade _propertly and simple._

**Comment by arjunyel** [comment]
One issue is TypeScript 5.0 lets you extend your tsconfig from multiple tsconfigs. `@bleed-believer/path-alias` assumes extends is a string, not an array

**Comment by sleep-written** [comment]
> One issue is TypeScript 5.0 lets you extend your tsconfig from multiple tsconfigs. `@bleed-believer/path-alias` assumes extends is a string, not an array

Thanks for the feedback, I'll take this change in consideration to update this library

**Comment by sleep-written** [comment]
Ok, the changes are ready (in theory) in [ts-update branch.](https://github.com/sleep-written/bleed-believer/tree/ts-update) The unit tests are ok, but I need to test more before to launch a new version, and update the documentation too. If anyone wants to test the package:

- Clone [ts-update branch.](https://github.com/sleep-written/bleed-believer/tree/ts-update)
- Install dependencies (this also transpiles the packages too):
  ```bash
  npm ci
  ```
- Install the package in your testing project using the package path:
  ```bash
  npm i --save ../bla/bla/bla/bleed-believer/packages/path-alias
  ```

> One issue is TypeScript 5.0 lets you extend your tsconfig from multiple tsconfigs. `@bleed-believer/path-alias` assumes extends is a string, not an array

Now the library it's capable to resolve arrays of extends, thanks for your comment!

**Comment by sleep-written** [comment]
Ok, finally the update has been [released!](https://www.npmjs.com/package/@bleed-believer/path-alias) About changes to take in consideration:
- Added support to extends from multiples files:
  `./tsconfig.json`
  ```json
  {
    "extends": [
        "../death/cube/k.json",
        "../dismember/antonella.json",
        "../wold/fauchion.json"
    ],
    "compilerOptions": {
      "...": "..."
    }
  }
  ```
- Changed the loader path: Now you must use `@bleed-believer/path-alias` instead of `@bleed-believer/path-alias/esm`:
  ```bash
  node --no-warnings --loader @bleed-believer/path-alias ./src/index.ts
  ```

if you found a problem with this release, open a new issue.
