### ISSUE TITLE
Allow for non-standard tsconfig paths

### ISSUE THREAD

**Issue by martin-mindflow** [sleep-written/bleed-believer#5]
Hi,

Would it be possible, using `@bleed-believer/path-alias`, to pass the path of the tsconfig file instated of using the default `./tsconfig.json` ? In our use case (an nx monorepo), the tsconfig is named `tsconfig.base.ts` and is not located in the same folder.

If you're opened to it and able to give me some pointers, i'm willing to create a pull request to address this :)

Thanks!

**Comment by sleep-written** [comment]
Hi, and thanks for your interest in contribute to this project! I'll some indications for you to make your PR:
- Create your PR from the [latest release.](https://github.com/sleep-written/bleed-believer/tree/v1.0.0)
- [This file](https://github.com/sleep-written/bleed-believer/blob/v1.0.0/packages/path-alias/src/tsconfig/tsconfig.ts) is the class that reads the `tsconfig.json` (you don't need to edit this). The class accepts __the path of the file__ as optional argument. You can considerate this to implement your function.
- In [this line](https://github.com/sleep-written/bleed-believer/blob/59204f73a0ab707323e6da3e12c06854c27a4a50/packages/path-alias/src/loader/resolver.ts#L9) is where the class is instanciated. You can put your custom configuration path in this line (as a constructor's argument).
- You can make your files inside `/src/tsconfig`, If your functionality requires more than 1 file (for example, 2 classes), put that files inside of a folder, for example `./src/my-folder`.
- Every file created by you, must have its own unit tests when it's possible.

**Comment by VirtuaBoza** [comment]
@martin-mindflow Have you got around to this or are you still planning to? I was surprised to find this issue closed but no linked PR/merge.

**Comment by martin-mindflow** [comment]
i had a branch that addressed this issue but since we've moved away from using ts-node i've never got around to pushing it :(
