### ISSUE TITLE
path-alias crashes on implicit `rootDir`

### ISSUE THREAD

**Issue by stwlam** [sleep-written/bleed-believer#6]
If a tsconfig has no explicit `rootDir`, src/tsconfig/tsconfig.ts will throw an exception upon trying to resolve it. Perhaps it should fall back to "." or `baseUrl`?

**Comment by stwlam** [comment]
Similarly, an absent `outDir`, which is not required and frequently omitted if not emitting, will lead to an identical type of crash.

**Comment by sleep-written** [comment]
Hi!
I was design the library making those fields required because that's the manner I work with typescript. For that case I specify this behavior in the [readme](https://github.com/sleep-written/bleed-believer/blob/master/packages/path-alias/README.md#configure-your-tsconfigjson):
> ### Configure your `tsconfig.json`
> 
> This package reads the `tsconfig.json` file (and is capable to find values if the file extends another configuration files) to declare the alias. A typical configuration coul be similar to this:
> ```json5
> {
>     "compilerOptions": {
>         "target": "es2022",
>         "module": "es2022", /* or "esnext" if you want (not tested yet) */
> 
>         "rootDir": "./src",
>         "outDir": "./dist",
> 
>         "baseUrl": "./src",
>         "paths": {
>             "@alias-a/*": ["./folder-a/*"],
>             "@alias-b/*": ["./folder-b/*"],
>         }
>     }
> }
> ```
> __The fields listed in the example of above are <u>all required</u> in order to the correct working of the package.__

But thinking in your suggestions as an expected behavior, it's a pretty good idea. So I'll reserve time in these days to analyze your suggestion and how to implement that in the library.

**Comment by sleep-written** [comment]
Ok, I created a new branch called ["path-alias"](https://github.com/sleep-written/bleed-believer/tree/path-alias) to work in this request. For now I created a new class to handle the reading of the configuration files:
- [TsconfigV2](https://github.com/sleep-written/bleed-believer/blob/path-alias/packages/path-alias/src/tsconfig/tsconfig-v2.ts).
- [Unit tests of that class](https://github.com/sleep-written/bleed-believer/blob/path-alias/packages/path-alias/src/tsconfig/tsconfig-v2.test.ts).
- [Usage cases.](https://github.com/sleep-written/bleed-believer/tree/path-alias/packages/path-alias/tsconfig-v2-tests)

Before to continue with the new feature, I need to validate if that form of generate the parameters in an implicit way is correct.

**Comment by sleep-written** [comment]
Ok, I crashed with a problem in ts-node:
- I made a simple project with this structure:
  ![imagen](https://user-images.githubusercontent.com/69736296/233476212-2af41571-8392-44e4-a164-b9cff77848d0.png)

- The `tsconfig.json` is this (watch the `"extends"` key):
  ```ts
  {
      "extends": [
          "./tsconfig.build.json",
          "./tsconfig.alias.json"
      ],
      "compilerOptions": {
          "target": "ES2022",
          "module": "ES2022",
  
          "esModuleInterop": true,
          "moduleResolution": "node",
          "emitDecoratorMetadata": true,
          "experimentalDecorators": true
      }
  }
  ```

- With this case, ts-node throws an error:
  ![imagen](https://user-images.githubusercontent.com/69736296/233477510-3ad27791-3c0b-44b9-8ef3-98fd7bfba970.png)

- The error occurs here:
  ![imagen](https://user-images.githubusercontent.com/69736296/233477896-2f7efd7d-c034-4c49-b3dd-95e16832b676.png)

As you can see, that function of ts-node has troubles with extends with an `Array` form. So the first step must be add that functionaly in ts-node prior to fix this problem. This problem doesn't occur when the `"extends"` property is an string.

**Comment by sleep-written** [comment]
@stwlam, your suggestion has been added into the package. Check the documentation before to use the updated version, and open a new issue if you have troubles.
