### ISSUE TITLE
Paths break when rootDir isn't specified but baseUrl is

### ISSUE THREAD

**Issue by neilenns** [sleep-written/bleed-believer#7]
My project has two main folders:

* src: the source for the actual app
* test: The unit test files (mocha)

![image](https://github.com/sleep-written/bleed-believer/assets/9524118/4a117dc8-48d0-4a40-90c2-9a82f6fa70e2)

I've set up paths for my major source folders like this:

```typescript
  "include": ["src/**/*", "test/**/*"],
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@models/*": ["models/*"],
      "@controllers/*": ["controllers/*"],
      "@routes/*": ["routes/*"],
      "@middleware/*": ["middleware/*"],
      "@configs/*": ["configs/*"],
      "@customTypes/*": ["types/*"],
      "@utils/*": ["utils/*"],
      "@services/*": ["services/*"],
      "@interfaces/*": ["interfaces/*"],
      "@app/*": ["./*"]
    },
 ...
 }
 ```
 
This makes vscode happy (it can properly know the imports in the test folder come from the src folder), makes mocha happy (it can successfully run all the tests when I include `"loader=@bleed-believer/path-alias"`, and makes eslint happy (I don't get errors about included files being outside of the rootDir).

Unfortunately it breaks running the actual app, as the imports wind up looking like this:

`server\dist\src\routes\activeFlightPlans.mjs`

Notice how `src` is inserted in to the module path when it shouldn't be there (there's no `src` folder on output to `dist`).

If I add `rootDir` back to the tsconfig.json it makes running the app work but makes a ton of eslint errors because all of my test files are outside of the rootDir.

Is there a way to make this work so the final paths for the actual app omit `src` from the import path?

**Comment by sleep-written** [comment]
I don't tested that scenario before, so i'll check this case to get a solution. So give me an example project with your actual configuration to test with your specific context.

**Comment by neilenns** [comment]
Attached is a small sample. I'll be honest, it's been a while since I looked at this and for some reason even in the sample I'm getting odd compile errors when building the tests that are likely unrelated to this issue. Regardless, here's how to use the sample:

1. Unzip and cd into the server directory
2. Run `npm install`
3. Run `npm run build` to build the app
4. Try `npm run start`

Result is an error saying the file can't be loaded. You can see the path includes `src` but my build produces everything in the top level of the `dist` folder.

If you remove the `baseUrl` property from `tsconfig.json` and try building and running again then the app will run correctly and output a `2` to the console. However if you then open `test/math.spec.mts` in vscode you'll get a red squiggle under the import saying it can't find the module.


[bleed-believer-test.zip](https://github.com/sleep-written/bleed-believer/files/12549791/bleed-believer-test.zip)

**Comment by sleep-written** [comment]
Excellent, i will check your project to understand where is the problem in my library.

**Comment by sleep-written** [comment]
I've tested `@bleed-believer/path-alias` in your project and encountered issues with `npm run test` and `npm run start`. Upon checking your configuration files, I identified the root cause. In short, your `tsconfig.json` is set to target `"ES2020"`, but `@bleed-believer/path-alias` requires `"ES2022"` (explained in [readme](https://github.com/sleep-written/bleed-believer/blob/master/packages/path-alias/README.md#configure-your-tsconfigjson)).

Your current `tsconfig.json` configuration is as follows:
```jsonc
{
  "ts-node": {
    "transpileOnly": false,
    // Required so .d.ts files will get recognized by Mocha
    "files": true
  },
  // The test folder has to be included here otherwise vscode
  // complains about the @ path references. It gets excluded
  // during production builds by the tsconfig-build.json file.
  "include": ["src/**/*", "test/**/*"],
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@utils/*": ["./utils/*"]
    },
    "target": "es2020" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
    "experimentalDecorators": true /* Enable experimental support for legacy experimental decorators. */,
    "emitDecoratorMetadata": true /* Emit design-type metadata for decorated declarations in source files. */,
    "module": "esnext" /* Specify what module code is generated. */,
    "moduleResolution": "node" /* Specify how TypeScript looks up a file from a given module specifier. */,
    "typeRoots": [
      "./types"
    ] /* Specify multiple folders that act like './node_modules/@types'. */,
    "resolveJsonModule": true /* Enable importing .json files. */,
    "sourceMap": true /* Create source map files for emitted JavaScript files. */,
    "outDir": "./dist" /* Specify an output folder for all emitted files. */,
    "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */,
    "forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,
    "strict": true /* Enable all strict type-checking options. */,
    "skipLibCheck": true /* Skip type checking all .d.ts files. */
  },
  "exclude": ["node_modules"]
}
```

For `@bleed-believer/path-alias` to work in your scenario, the `tsconfig.json` should resemble:
```json
{
    "compilerOptions": {
        "module": "ES2022",
        "target": "ES2022",
        "strict": true,

        "verbatimModuleSyntax": true,
        "moduleResolution": "node",
        "esModuleInterop": true,

        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "sourceMap": true,

        "baseUrl": ".",
        "paths": {
            "@test/*": [ "./test/*" ],
            "@app/*": [ "./app/*" ]
        }
    }
}
```

I've created an [example project](https://github.com/sleep-written/bleed-believer/tree/master/examples/path-alias-mocha) that mirrors your project's structure. If you'd like to run it without cloning and building the entire repository, you can download [this zip with the example project](https://github.com/sleep-written/bleed-believer/files/12559205/path-alias-mocha.zip) and follow the steps below:
- Install the necessary dependencies:
  ```bash
  npm ci
  ```
- Execute the project:
  ```bash
  npm run start
  ```
- Run the unit tests:
  ```bash
  npm run test
  ```

**Comment by neilenns** [comment]
Thanks for the detailed reply and for the sample project. I took a peek and it's quite different from the one I provided. It doesn't have a build step that transpiles to javascript (as mine does). It's just running the .mts file directly instead of the transpiled javascript from the `dist` folder.

I did try changing my sample to use es2022 modules and that didn't make the path problem go away.

I believe the issue is instead related to how I have two tsconfig files: one for development time (tsconfig.json) and one for release build time (tsconfig-build.json). The second one omits the `test` folder so the resulting `dist` folder does *not* have a `src` subdirectory in it.

![image](https://github.com/sleep-written/bleed-believer/assets/9524118/149fde66-068c-4c74-b726-387049d8668f)

However, the path generated by bleed-believer does:

`D:\git\bleed-believer-test\server\dist\src\utils\math.mjs`.

I need some way to tell bleed-believer at runtime to *not* include the `baseUrl` part of the path in the path mapping.

**Comment by sleep-written** [comment]
Ok, I updated the example, and now has a build process. [Here's the example updated](https://github.com/sleep-written/bleed-believer/files/12561930/path-alias-mocha.zip). Check the `package.json` for the additional commands.

To make a successful build, use `"moduleResolution": "Node"` instead of `"Node16"`.

**Comment by neilenns** [comment]
Thanks for the updated sample. I can see some places where it differs from how I have mine structured. Unfortunately the updated example doesn't work on Windows when I do `npm run start:dist`:

`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'`

**Comment by neilenns** [comment]
If you want to see the actual files I'm using instead of the made-up sample they are here: https://github.com/neilenns/vatsim-plan-verifier/tree/neilenns/issue514. Only the stuff in the `server` folder is relevant.

In my current build I have the following in `tsconfig.json`:

```javascript
  "include": ["src/**/*", "test/**/*"],
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@models/*": ["./src/models/*"],
      "@controllers/*": ["./src/controllers/*"],
      "@routes/*": ["./src/routes/*"],
      "@middleware/*": ["./src/middleware/*"],
      "@configs/*": ["./src/configs/*"],
      "@customTypes/*": ["./src/types/*"],
      "@utils/*": ["./src/utils/*"],
      "@services/*": ["./src/services/*"],
      "@interfaces/*": ["./src/interfaces/*"],
      "@app/*": ["./src/*"]
    },
    "target": "es2020",
    "module": "esnext",
    "moduleResolution": "node"
```

and the following in `tsconfig-build.json`:

```javascript
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "rootDir": "./src"
  },
  "exclude": ["test/**/*"]
}
```

After building the app then running I get this error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\git\vatsim-plan-verifier\server\dist\src\routes\activeFlightPlans.mjs' imported from D:\git\vatsim-plan-verifier\server\dist\server.mjs
```

Notice that it includes `src` in the path. It doesn't matter what I change `target`, `module`, or `nodeResolution` to, it still gives me the path error because it includes `src` in the path.

Note that I am not using `bb-path-alias` to run. I'm using the following:

```
node --loader @bleed-believer/path-alias ./dist/main.mjs
```

**Comment by neilenns** [comment]
I tried switching to `bb-path-alias` and that results in the same error I received with your sample:

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'      
```

**Comment by sleep-written** [comment]
> If you want to see the actual files I'm using instead of the made-up sample they are here: https://github.com/neilenns/vatsim-plan-verifier/tree/neilenns/issue514. Only the stuff in the `server` folder is relevant.
> 
> In my current build I have the following in `tsconfig.json`:
> 
> ```js
>   "include": ["src/**/*", "test/**/*"],
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@models/*": ["./src/models/*"],
>       "@controllers/*": ["./src/controllers/*"],
>       "@routes/*": ["./src/routes/*"],
>       "@middleware/*": ["./src/middleware/*"],
>       "@configs/*": ["./src/configs/*"],
>       "@customTypes/*": ["./src/types/*"],
>       "@utils/*": ["./src/utils/*"],
>       "@services/*": ["./src/services/*"],
>       "@interfaces/*": ["./src/interfaces/*"],
>       "@app/*": ["./src/*"]
>     },
>     "target": "es2020",
>     "module": "esnext",
>     "moduleResolution": "node"
> ```

You are using ES2020, when __this package works with ES2022.__

**Comment by neilenns** [comment]
I understand. As I mentioned earlier:

> I did try changing my sample to use es2022 modules and that didn't make the path problem go away.

It makes no difference whether I use es2020, es2022 or esnext. They all result in the same problem.

**Comment by sleep-written** [comment]
Show me your tsconfig using ES2022 in target

**Comment by neilenns** [comment]
I tried swapping to ES2022 again and am getting errors from mongoose now. I appreciate your attempts to resolve this but am going to close the issue. I'm just going to stay with full paths for now.
