### ISSUE TITLE
[path-alias] The requested module 'node:module' does not provide an export named 'register'

### ISSUE THREAD

**Issue by slavafomin** [sleep-written/bleed-believer#9]
Hello!

Thank you for this great library!

However, I'm having the following error:

```
import { register } from 'node:module';
         ^^^^^^^^
SyntaxError: The requested module 'node:module' does not provide an export named 'register'
```

I'm running it like this: `TS_NODE_PROJECT=tsconfig.app.json node --import @bleed-believer/path-alias ./file.ts`

```
node 18.18.2
```

Thanks!

**Comment by sleep-written** [comment]
Hi, and thanks for using my library!
The version v1.0.0 of @bleed-believer/path-alias is intended for node v20 or later. In your environment, use [this version](https://www.npmjs.com/package/@bleed-believer/path-alias/v/0.15.2) instead.
Also, the environment variable `TS_NODE_PROJECT` isn't supported by this library, but in a future release i would consider add an environment variable to use another configuration file.

Regards.
